settings:
  world: "world"
  search-radius: 5000
  default-timer: 3600

chances:
  mystic: 40
  golem: 40
  vote: 20

golem:
  health: 1000
  schematic: "golem_arena.schem"
  donate-command: "playerpoints give %player% %amount%"
  rewards:
    coins-min: 0
    coins-max: 9990
    donate-min: 0
    donate-max: 3

messages:
  prefix: "&#FF6600[HHEvents] &f"
  mystic-spawn: "Мистик появился на координатах X: %x%, Y: %y%, Z: %z%!"
  golem-spawn: "Голем появился на координатах X: %x%, Y: %y%, Z: %z%!"
  event-end: "Ивент завершен!"
  bossbar: "&eИвент: %name% &8| &cРедкость: %rarity% &8| &a%time% сек"
