name: HHEvents
version: '1.0.0'
main: ua.atherium.hhevents.HHEvents
api-version: 1.13
authors: [ Oleze_bebidjonov ]
description: Универсальная система ивентов для 1.16.5
depend: [ Vault, FastAsyncWorldEdit ]

commands:
  event:
    description: Основная команда системы ивентов
    aliases: [ events, hhevent ]
    permission: hhevents.admin
    usage: /event

permissions:
  hhevents.admin:
    description: Полный доступ к командам администратора HHEvents
    default: op